import {
  WordIcon,
  PdfIcon,
  ExcelIcon,
  ExcelToPdfIcon,
  JpgIcon,
  PngIcon,
  PdfToJpgIcon,
  PdfToPngIcon,
  MergePdfIcon,
  SplitPdfIcon,
  CompressPdfIcon,
  RotatePdfIcon,
  ProtectPdfIcon,
  UnlockPdfIcon,
  OcrIcon,
  PdfEditorIcon,
} from '../components/FormatIcons';
import type { ToolConfig, ToolCategory } from '../types';

export const categories: readonly string[] = [
  'All',
  'Documents',
  'PDF',
  'Images',
  'Compression',
  'Security',
  'OCR',
] as const;

export const tools: ToolConfig[] = [
  {
    id: 'pdf-to-word',
    name: 'PDF → Word',
    description: 'Convert PDF documents into editable Word files.',
    inputFormat: 'PDF',
    outputFormat: 'DOCX',
    accepted: ['application/pdf', '.pdf'],
    category: 'Documents',
    icon: WordIcon,
    route: '/tools/pdf-to-word',
    accent: 'blue',
    apiEndpoint: '/api/convert/pdf-to-word',
  },
  {
    id: 'word-to-pdf',
    name: 'Word → PDF',
    description: 'Turn Word documents into polished PDFs.',
    inputFormat: 'DOCX',
    outputFormat: 'PDF',
    accepted: [
      'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
      '.docx',
    ],
    category: 'Documents',
    icon: PdfIcon,
    route: '/tools/word-to-pdf',
    accent: 'red',
    apiEndpoint: '/api/convert/word-to-pdf',
  },
  {
    id: 'pdf-to-excel',
    name: 'PDF → Excel',
    description: 'Extract tables from PDF into spreadsheets.',
    inputFormat: 'PDF',
    outputFormat: 'XLSX',
    accepted: ['application/pdf', '.pdf'],
    category: 'Documents',
    icon: ExcelIcon,
    route: '/tools/pdf-to-excel',
    accent: 'green',
    apiEndpoint: '/api/convert/pdf-to-excel',
  },
  {
    id: 'excel-to-pdf',
    name: 'Excel → PDF',
    description: 'Share spreadsheets as clean PDF documents.',
    inputFormat: 'XLSX',
    outputFormat: 'PDF',
    accepted: [
      'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
      '.xlsx',
    ],
    category: 'Documents',
    icon: ExcelToPdfIcon,
    route: '/tools/excel-to-pdf',
    accent: 'green',
    apiEndpoint: '/api/convert/excel-to-pdf',
  },
  {
    id: 'jpg-to-pdf',
    name: 'JPG → PDF',
    description: 'Combine JPG images into a single PDF.',
    inputFormat: 'JPG',
    outputFormat: 'PDF',
    accepted: ['image/jpeg', '.jpg', '.jpeg'],
    category: 'Images',
    icon: JpgIcon,
    route: '/tools/jpg-to-pdf',
    accent: 'orange',
    apiEndpoint: '/api/convert/jpg-to-pdf',
    multiple: true,
  },
  {
    id: 'png-to-pdf',
    name: 'PNG → PDF',
    description: 'Create a PDF from crisp PNG images.',
    inputFormat: 'PNG',
    outputFormat: 'PDF',
    accepted: ['image/png', '.png'],
    category: 'Images',
    icon: PngIcon,
    route: '/tools/png-to-pdf',
    accent: 'purple',
    apiEndpoint: '/api/convert/png-to-pdf',
    multiple: true,
  },
  {
    id: 'pdf-to-jpg',
    name: 'PDF → JPG',
    description: 'Export PDF pages as high-quality JPG images.',
    inputFormat: 'PDF',
    outputFormat: 'JPG',
    accepted: ['application/pdf', '.pdf'],
    category: 'Images',
    icon: PdfToJpgIcon,
    route: '/tools/pdf-to-jpg',
    accent: 'orange',
    apiEndpoint: '/api/convert/pdf-to-jpg',
  },
  {
    id: 'pdf-to-png',
    name: 'PDF → PNG',
    description: 'Export PDF pages as transparent PNG images.',
    inputFormat: 'PDF',
    outputFormat: 'PNG',
    accepted: ['application/pdf', '.pdf'],
    category: 'Images',
    icon: PdfToPngIcon,
    route: '/tools/pdf-to-png',
    accent: 'purple',
    apiEndpoint: '/api/convert/pdf-to-png',
  },
  {
    id: 'merge-pdf',
    name: 'Merge PDF',
    description: 'Join multiple PDFs into one organized file.',
    inputFormat: 'PDF',
    outputFormat: 'PDF',
    accepted: ['application/pdf', '.pdf'],
    category: 'PDF',
    icon: MergePdfIcon,
    route: '/tools/merge-pdf',
    accent: 'red',
    apiEndpoint: '/api/pdf/merge',
    multiple: true,
  },
  {
    id: 'split-pdf',
    name: 'Split PDF',
    description: 'Separate pages or ranges into new PDFs.',
    inputFormat: 'PDF',
    outputFormat: 'PDF',
    accepted: ['application/pdf', '.pdf'],
    category: 'PDF',
    icon: SplitPdfIcon,
    route: '/tools/split-pdf',
    accent: 'red',
    apiEndpoint: '/api/pdf/split',
  },
  {
    id: 'compress-pdf',
    name: 'Compress PDF',
    description: 'Reduce PDF size while keeping it readable.',
    inputFormat: 'PDF',
    outputFormat: 'PDF',
    accepted: ['application/pdf', '.pdf'],
    category: 'Compression',
    icon: CompressPdfIcon,
    route: '/tools/compress-pdf',
    accent: 'teal',
    apiEndpoint: '/api/pdf/compress',
  },
  {
    id: 'ocr',
    name: 'OCR PDF',
    description: 'Make scanned documents searchable and editable.',
    inputFormat: 'PDF / Image',
    outputFormat: 'PDF / TXT',
    accepted: [
      'application/pdf',
      'image/jpeg',
      'image/png',
      '.pdf',
      '.jpg',
      '.jpeg',
      '.png',
    ],
    category: 'OCR',
    icon: OcrIcon,
    route: '/tools/ocr',
    accent: 'blue',
    apiEndpoint: '/api/pdf/ocr',
  },
  {
    id: 'rotate-pdf',
    name: 'Rotate PDF',
    description: 'Fix page orientation in seconds.',
    inputFormat: 'PDF',
    outputFormat: 'PDF',
    accepted: ['application/pdf', '.pdf'],
    category: 'PDF',
    icon: RotatePdfIcon,
    route: '/tools/rotate-pdf',
    accent: 'blue',
    apiEndpoint: '/api/pdf/rotate',
  },
  {
    id: 'protect-pdf',
    name: 'Protect PDF',
    description: 'Add a password to keep a PDF private.',
    inputFormat: 'PDF',
    outputFormat: 'PDF',
    accepted: ['application/pdf', '.pdf'],
    category: 'Security',
    icon: ProtectPdfIcon,
    route: '/tools/protect-pdf',
    accent: 'orange',
    apiEndpoint: '/api/pdf/protect',
  },
  {
    id: 'unlock-pdf',
    name: 'Unlock PDF',
    description: 'Remove known restrictions from a PDF.',
    inputFormat: 'PDF',
    outputFormat: 'PDF',
    accepted: ['application/pdf', '.pdf'],
    category: 'Security',
    icon: UnlockPdfIcon,
    route: '/tools/unlock-pdf',
    accent: 'green',
    apiEndpoint: '/api/pdf/unlock',
  },
  {
    id: 'pdf-editor',
    name: 'PDF Editor',
    description: 'Annotate, rotate, and organize PDF pages.',
    inputFormat: 'PDF',
    outputFormat: 'PDF',
    accepted: ['application/pdf', '.pdf'],
    category: 'PDF',
    icon: PdfEditorIcon,
    route: '/tools/pdf-editor',
    accent: 'purple',
    apiEndpoint: '/api/pdf/edit',
  },
];
